- hosts: webservers 
  tasks:
    - name: install apache2 
      apt: 
        name: apache2 
        state: latest
    - name: start  apache2
      systemd: 
        name: apache2
        state: started
    - name: copy index.html
      copy: 
        src: /tmp/index.html
        dest: /var/www/html/
  handlers:
    - name: restart
