# This must be created first before any deployments in 
# which this secret is referenced can be created

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
   mongo_root_username: dXNlcm5hbWU=
   mongo_root_password: cGFzc3dvcmQ=
